version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.9"
python:
  install:
    - requirements: docs/source/requirements.txt
    - method: pip
      path: .
      extra_requirements:
        - docs

sphinx:
  builder: html
  configuration: docs/source/conf.py
