[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "IPython",
    "oldest-supported-numpy",
    "pandas",
    "matplotlib",
    "seaborn",
    "H2MM_C"
]
build-backend = "setuptools.build_meta"
