name: Tests

on: [push]

jobs:
  build:

    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.8", "3.9", "3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Setup Python ${{matrix.python-version}}
        uses: actions/setup-python@v4
        with:
          python-version: ${{matrix.python-version}}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pytest numpy cython pandas matplotlib seaborn lmfit h2mm-c
          python -m pip install fretbursts
      - name: Download Files Unix
        if: runner.os != 'Windows'
        run: |
          wget -N https://zenodo.org/record/5902313/files/HP3_TE300_SPC630.hdf5
          wget -N https://figshare.com/ndownloader/files/4858417 -O HairPin3_RT_400mM_NaCl_A_31_TA.hdf5
      - name: Download files Windows
        if: runner.os == 'Windows'
        run: |
           curl.exe --output HP3_TE300_SPC630.hdf5 --url https://zenodo.org/record/5902313/files/HP3_TE300_SPC630.hdf5
           curl.exe -L --output HairPin3_RT_400mM_NaCl_A_31_TA.hdf5 --url https://figshare.com/ndownloader/files/4858417
      - name: Test with pytest
        run: python -m pytest
